### ISSUE TITLE
can not install on ubuntu

### ISSUE THREAD

**Issue by tarasbogach** [dimikot/dklab_realplexor#1]
sudo su
chkconfig --add dklab_realplexor
insserv: warning: script 'K01gdm' missing LSB tags and overrides
insserv: warning: script 'S19linux-restricted-modules-common' missing LSB tags and overrides
insserv: warning: script 'K01acpi-support' missing LSB tags and overrides
insserv: warning: current start runlevel(s) (0 6) of script `sendsigs' overwrites defaults (empty).
insserv: warning: current start runlevel(s) (0 6) of script`wpa-ifupdown' overwrites defaults (empty).
insserv: warning: current stop runlevel(s) (1) of script `policykit' overwrites defaults (empty).
insserv: warning: script 'acpi-support' missing LSB tags and overrides
insserv: warning: current start runlevel(s) (0 6) of script`umountroot' overwrites defaults (empty).
insserv: warning: script 'gdm' missing LSB tags and overrides
insserv: warning: current stop runlevel(s) (0 1 6) of script `apport' overwrites defaults (empty).
insserv: warning: current start runlevel(s) (0) of script`halt' overwrites defaults (empty).
insserv: script postgresql-8.4: service postgresql already provided!
insserv: script postgresql-8.4: service postgresql-8.4 already provided!
insserv: warning: current start runlevel(s) (6) of script `reboot' overwrites defaults (empty).
insserv: warning: current start runlevel(s) (0 6) of script`umountfs' overwrites defaults (empty).
insserv: warning: current start runlevel(s) (0 6) of script `umountnfs.sh' overwrites defaults (empty).
insserv: warning: script 'linux-restricted-modules-common' missing LSB tags and overrides
insserv: warning: current stop runlevel(s) (1) of script`ufw' overwrites defaults (empty).
dklab_realplexor          0:off  1:off  2:on   3:on   4:on   5:on   6:off
root@taras-laptop:/home/taras# chkconfig dklab_realplexor on
root@taras-laptop:/home/taras# service dklab_realplexor start
FAILED: /etc/dklab_realplexor.conf; see logs

**Comment by dimikot** [comment]
Please see /var/log/syslog (or /var/log/messages or /var/log/\* - I don't know how your syslog is configured) to determine why Realplexor cannot start.

**Comment by tarasbogach** [comment]
sudo su - solves the problem
