### ISSUE TITLE
какие браузеры потдерживают realplexor?

### ISSUE THREAD

**Issue by maxgu** [dimikot/dklab_realplexor#10]
клиентская сторона (и данный тип соединения) работает во всех браузерах?
работает ли на мобильных устройсвах?

**Comment by dimikot** [comment]
Все, где есть XMLHttpRequest (т.е. все современные, начиная с IE6). В этом вся соль. На мобильных браузерах - должен работать тоже (кроме Opera Mobile, конечно, в котором страницы рендерятся на сервере и посылаются на телефон уже картинками)..
