### ISSUE TITLE
Проблема при компиляции cpp версии

### ISSUE THREAD

**Issue by 995533** [dimikot/dklab_realplexor#15]
Здравствуйте 

пытаюсь собрать под CentOS 6.2 
не могу скомпилировать cpp версию 

In file included from dklab_realplexor.cpp:76: 
utils/ev++0x.h:4:18: error: ev++.h: Нет такого файла или каталога 
In file included from dklab_realplexor.cpp:71: 
utils/misc.h: In function ‘void die(std::string)’: 
utils/misc.h:83: ошибка: expected primary-expression before ‘[’ token 
компиляция прервана из за ошибок -Wfatal-errors. 

Все пакеты стоят включая libev 

как быть

**Comment by dimikot** [comment]
Инструкции по сборке - в комментариях прямо внутри Make.sh:
https://github.com/DmitryKoterov/dklab_realplexor/blob/master/cpp/src/Make.sh

Там нужно зависимости поставить вначале, да и новый GCC тоже.
