### ISSUE TITLE
Не собирается C++ версия на CentOS

### ISSUE THREAD

**Issue by ramilexe** [dimikot/dklab_realplexor#17]
Дмитрий, доброе утро. Пытаюсь собрать с++ версию на CentOS и выдается следующая ошибка:

``` bash
[root@redmin src]# ./Make.sh 
In file included from dklab_realplexor.cpp:86:0:
Storage/CleanupTimers.h: В функции-члене «void Storage::CleanupTimers::start_timer_for_id(Realplexor::ident_t, int, Cb)»:
Storage/CleanupTimers.h:31:26: ошибка: capture of non-variable «Storage::CleanupTimers::storage» 
компиляция прервана из-за -Wfatal-errors.
```

Если в Storage/CleanupTimers.h на строке 26 заменить

```
if (storage.count(id)) {
```

на 

```
if (this->storage.count(id)) {
```

, то на данную строчку уже не ругается.

Версия компилятора:

``` bash
[root@redmin src]# g++ -v
Используются внутренние спецификации.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.7.0/lto-wrapper
Целевая архитектура: x86_64-unknown-linux-gnu
Параметры конфигурации: ./configure --with-mpc-lib=/usr/local/lib --with-gmp=/usr/local/lib --with-mpfr=/usr/local/lib --enable-languages=c,c++ --without-ppl --without-cloog
Модель многопоточности: posix
gcc версия 4.7.0 20120314 (prerelease) (GCC)
```

**Comment by dimikot** [comment]
Похоже на баг в компиляторе (вернее даже не столько баг, сколько побочный эффект оптимизатора), как это ни смешно. Как замена в строчке "storage.count(id)" может влиять на строчку "auto wrapper = [&storage, callback, id](int) {}" ?

```
map<ident_t, shared_ptr<Realplexor::Event::ITimer>> storage;

public:

CleanupTimers() {}

template<typename Cb>
void start_timer_for_id(ident_t id, int timeout, Cb callback)
{
    // Remove current timer if present.
    if (storage.count(id)) {
        storage[id]->remove();
        storage.erase(id);
    }
    // Create new timer.
    auto wrapper = [&storage, callback, id](int) { 
        auto guard = storage[id];
        storage.erase(id); // thanks to guard, the timer is deleted only when we exit this closure
        callback(); // it is important for logs to call erase() before the callback
    };
    storage[id].reset(new Realplexor::Event::Timer<decltype(wrapper)>(wrapper));
    storage[id]->start(timeout);
}
```

Вот я нашел насчет этого: http://gcc.gnu.org/ml/gcc-help/2012-02/msg00203.html

Попробуйте сделать, как там написано, т.е. заменить на

```
auto wrapper = [this, callback, id](int) { 
```

Первую строчку, где storage.count(id), не меняйте - с ней все в порядке, нет смысла добавлять там "this->".

Если получится, сделайте pull request, я вмерджу. Спасибо!

**Comment by ZooKeeper** [comment]
```
auto wrapper = [this, callback, id](int) { 
```

дает 

```
Storage/CleanupTimers.h: In lambda function:
Storage/CleanupTimers.h:32:36: error: no match for 'operator[]' in '((Storage::CleanupTimers*)this)->Storage::CleanupTimers::storage[id]'
```

Проще всего Вам попробовать собрать с последними версиями пакетов, как видно из тредов это не изолированные проблемы, а изменившееся поведение gcc

**Comment by timosha** [comment]
https://github.com/Timosha/dklab_realplexor/commit/a4baf8fa65085ff4e507a1a0e54ba139ed0e4b56 и https://github.com/Timosha/dklab_realplexor/commit/b8bd2b71de4c65948686c7830f3cf430fd80cc5b позволяют собрать для gcc 4.7.2, после выхода 4.7.3 второе изменение можно убрать

**Comment by dimikot** [comment]
Данные коммиты вмерджены в основную ветку.
