### ISSUE TITLE
dklab_realplexor.js bug - subdomain check fail

### ISSUE THREAD

**Issue by tarasbogach** [dimikot/dklab_realplexor#2]
Subdomain check on lines 37-40 in dklab_realplexor.js is fail
page url is http://dklab_realplexor/
realplexor url is http://rpl.dklab_realplexor:8088/
All works great if I comment out lines 37-40 in dklab_realplexor.js

**Comment by dimikot** [comment]
Domain name must not contain "_", it is an invalid character. And the port number must be the same for both pages to work in all brosers.
