### ISSUE TITLE
OS X installation

### ISSUE THREAD

**Issue by rinatio** [dimikot/dklab_realplexor#25]
Hello, Dmitry  

Are there any Mac OS X installation manual around? Also are there any English introduction? I'm trying to promote this library in my US company, but my manager said: "His homepage is in russian with english version leading nowhere".  

Thanks

**Comment by ZooKeeper** [comment]
I'll make an instruction for brew as soon as I'll get it to compile. There are some unresolved issues.

**Comment by dimikot** [comment]
Officially only Linux is supported.
