### ISSUE TITLE
Firefox 4.0 fix: attempt to run compile-and-go script on a cleared scope

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [dimikot/dklab_realplexor#4]
Browser: Firefox 4.0

В Js-коде внутри iframe на строке 256 кидается исключение: "attempt to run compile-and-go script on a cleared scope"

Решение: очищать обрабочик "onreadystatechange" перед вызовом "abort".

Патч:

<pre>
--- dklab_realplexor.html   (revision 523)
+++ dklab_realplexor.html   (working copy)
@@ -276,6 +276,7 @@
            // and reaches the connection limit.
            try { 
                if (th._lastXmlhttp) {
+                   th._lastXmlhttp.onreadystatechange = function(){};
                    th._lastXmlhttp.abort();
                    th._lastXmlhttp = null;
                }
@@ -284,6 +285,7 @@
        if (this._lastXmlhttp) {
            var xhr = this._lastXmlhttp;
            this._lastXmlhttp = null;
+           xhr.onreadystatechange = function(){};
            xhr.abort();  // abort() does not make bounce if this._lastXmlhttp is null
        }
        this._namespace = namespace && namespace.length? namespace : null;

</pre>

**Comment by dimikot** [comment]
Thanks, fixed.
https://github.com/DmitryKoterov/dklab_realplexor/commit/fa1f70c684b7a61820ee2ff6e9515ca56593666d
