### ISSUE TITLE
Unsubsribing from all channels causes bounces

### ISSUE THREAD

**Issue by kulbakin** [dimikot/dklab_realplexor#5]
Background: i have an application which i'd like to halt all client side activity on a certain occasion, i.e. stop receiving updates  from server (but sure without reloading the page). My actions are to remove all event handler subscriptions with `unsubscribe` calls.
The problem is that when all handlers are removed (i.e. there is no channels to listen for javascript side), javascript still tries to listen with empty `identifier` parameter in GET, which causes server side to return `502 Bad Gateway` response (i have nginx+apache setup).
Checked online sandbox http://realtime.rutvit.ru/?identifier=&ncrnd=13066977517 and it gives the same error (so i figured it's not about my configuration :)
As i understand, the issue is not in server side, but in javasript keeping long pulling requests even when there is nothing to listen to.
It would be great to have an option to terminate long pulling so no new connection is made to the server.

**Comment by dimikot** [comment]
Good catch. I'll fix it when I have some time (with low priority).

**Comment by dimikot** [comment]
Fixed.
