### ISSUE TITLE
проблема с изменением document.domain

### ISSUE THREAD

**Issue by kkamkou** [dimikot/dklab_realplexor#8]
Дмитрий, здравствуйте.

Появилась такая проблема в... IE7 - плексор меняет document.domain, после чего перестают работать iframe, которые идут после инициализации плексора. Т.е. вызов на них: iframe.contentWindow.document... возвращает ошибку доступа.

Подскажите пожалуйста, как обойти текущую проблему. Может быть можно как-то вручную вызывать изменение document.domain? Или флаг какой-нибудь, который будет выставлять домен по необходимости?

**Comment by dimikot** [comment]
Браузеры обычно ограничивают число одновременных соединений к каждому домену, поэтому важно, чтобы реалплексор висел на отдельном домене. Отсюда и все пляски с document.domain.

Почитайте в форуме http://forum.dklab.ru/viewtopic.php?t=36149 - кажется, там был вариант решения, когда document.domain не изменяется (но в этом случае вам а) потребуется поставить nginx перед сайтом и реалплексором, чтобы реалплексор отвечал на подURLе сайта, а не на поддомене, и б) придется мириться с ограничением на число коннектов - один коннект будет постоянно съедать реалплексор, из-за чего скорость загрузки сайта пострадает).

**Comment by degtyaryov** [comment]
В документе страницы http://mydomain.ru dklab_realplexor.js выполняет <script>document.domain = 'mydomain.ru';</script>

Поэтому любой iframe на странице должен сделать тоже самое, чтобы браузер считал что ифрейм свой, что является гарантом безопасности.
в iframe http://comet.mydomain.ru так же выполняется <script>document.domain = 'mydomain.ru';</script> и он работает.

В своих iframe'ах добавьте <script>document.domain = 'mydomain.ru';</script> и всё должно работать.

**Comment by kkamkou** [comment]
Сколько кровушки выпил IE7 из меня, в том числе и вышеописанного разлива :). Дело в том, что доступа к document.open() у меня нет. IE7 просто не дает это сделать. А если использовать 

```
iframe.src = 'javascript:(function(){document.open();document.domain="' + document.domain + '";document.close();})()';
```

, то iframe забывает свой doc.location.hash после этих манипуляций. Конкретная задача, которая стояла - использовать на домене с dklab_realplexor, history.js. Было это в ноябре еще. И решить задачу так и не удалось. С автором плагина договорились просто отключать history.js в этом случае.

Поэтому, если можно, не закрывайте пожалуйста тикет. Может кто-нибудь найдет решение.

**Comment by GChernikov** [comment]
Сейчас как раз возникла данная проблема.. Вопреки мнению автора считаю, что переопределение document.domain это такой хак, который в будущем еще будет неизвестно как аукаться.. 

Возможным решением было бы использование какого-либо из способов кроссдоменной передачи информации (есть куча информации на эту тему 
http://it.nittis.ru/iframe-xss.html
http://javascript.ru/ajax/cross-domain-scripting
http://javascript.ru/ajax/cross-origin-2)

Как написали вот в этом комментарии
http://forum.dklab.ru/viewtopic.php?p=198010#198010

общение с iframe с другого домена можно реализовать через postMessage (а он уже шлет XHR). Правда работать это будет только в FF3+, IE8+, Chrome, Safari(5?), Opera10+

Но писать указанное выше решение у меня банально не хватает сейчас времени.. Поэтому лично для себя я выбрал решение, о котором здесь упомянул автор: realplexor вешается просто на отдельный url (а не на поддомен), таким образом скорость дальнейшей загрузки страницы (после установки соединения с комет-сервером) приносится в жертву.

**Comment by kkamkou** [comment]
@DmitryKoterov тикет можно закрыть я думаю. Спасибо.
@GChernikov см. easyXDM
